### ISSUE TITLE
following the instructions npm-debug.log

### ISSUE THREAD

**Issue by foxjazz** [r-park/todo-angular2-firebase#116]
info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.3
3 info using node@v6.7.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle todo-angular2-firebase@0.8.0~prebuild: todo-angular2-firebase@0.8.0
6 verbose lifecycle todo-angular2-firebase@0.8.0~prebuild: unsafe-perm in lifecycle true
7 verbose lifecycle todo-angular2-firebase@0.8.0~prebuild: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;G:\code\memberships\membercode\node_modules\.bin;C:\Program Files\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\IDM Computer Solutions\UltraCompare;C:\Program Files\IDM Computer Solutions\UltraEdit;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Users\fox21\AppData\Local\Microsoft\WindowsApps;;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\fox21\AppData\Roaming\npm
8 verbose lifecycle todo-angular2-firebase@0.8.0~prebuild: CWD: G:\code\memberships\membercode
9 silly lifecycle todo-angular2-firebase@0.8.0~prebuild: Args: [ '/d /s /c', 'run-s clean:target test' ]
10 silly lifecycle todo-angular2-firebase@0.8.0~prebuild: Returned: code: 0  signal: null
11 info lifecycle todo-angular2-firebase@0.8.0~build: todo-angular2-firebase@0.8.0
12 verbose lifecycle todo-angular2-firebase@0.8.0~build: unsafe-perm in lifecycle true
13 verbose lifecycle todo-angular2-firebase@0.8.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;G:\code\memberships\membercode\node_modules\.bin;C:\Program Files\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\IDM Computer Solutions\UltraCompare;C:\Program Files\IDM Computer Solutions\UltraEdit;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Users\fox21\AppData\Local\Microsoft\WindowsApps;;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\fox21\AppData\Roaming\npm
14 verbose lifecycle todo-angular2-firebase@0.8.0~build: CWD: G:\code\memberships\membercode
15 silly lifecycle todo-angular2-firebase@0.8.0~build: Args: [ '/d /s /c',
15 silly lifecycle   'cross-env NODE_ENV=production webpack --display-chunks --progress' ]
16 silly lifecycle todo-angular2-firebase@0.8.0~build: Returned: code: 0  signal: null
17 info lifecycle todo-angular2-firebase@0.8.0~postbuild: todo-angular2-firebase@0.8.0
18 verbose lifecycle todo-angular2-firebase@0.8.0~postbuild: unsafe-perm in lifecycle true
19 verbose lifecycle todo-angular2-firebase@0.8.0~postbuild: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;G:\code\memberships\membercode\node_modules\.bin;C:\Program Files\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\IDM Computer Solutions\UltraCompare;C:\Program Files\IDM Computer Solutions\UltraEdit;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Users\fox21\AppData\Local\Microsoft\WindowsApps;;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\fox21\AppData\Roaming\npm
20 verbose lifecycle todo-angular2-firebase@0.8.0~postbuild: CWD: G:\code\memberships\membercode
21 silly lifecycle todo-angular2-firebase@0.8.0~postbuild: Args: [ '/d /s /c', './bin/postbuild.copy-assets.sh' ]
22 silly lifecycle todo-angular2-firebase@0.8.0~postbuild: Returned: code: 1  signal: null
23 info lifecycle todo-angular2-firebase@0.8.0~postbuild: Failed to exec postbuild script
24 verbose stack Error: todo-angular2-firebase@0.8.0 postbuild: `./bin/postbuild.copy-assets.sh`
24 verbose stack Exit status 1
24 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
24 verbose stack     at emitTwo (events.js:106:13)
24 verbose stack     at EventEmitter.emit (events.js:191:7)
24 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
24 verbose stack     at emitTwo (events.js:106:13)
24 verbose stack     at ChildProcess.emit (events.js:191:7)
24 verbose stack     at maybeClose (internal/child_process.js:877:16)
24 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
25 verbose pkgid todo-angular2-firebase@0.8.0
26 verbose cwd G:\code\memberships\membercode
27 error Windows_NT 10.0.14393
28 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
29 error node v6.7.0
30 error npm  v3.10.3
31 error code ELIFECYCLE
32 error todo-angular2-firebase@0.8.0 postbuild: `./bin/postbuild.copy-assets.sh`
32 error Exit status 1
33 error Failed at the todo-angular2-firebase@0.8.0 postbuild script './bin/postbuild.copy-assets.sh'.
33 error Make sure you have the latest version of node.js and npm installed.
33 error If you do, this is most likely a problem with the todo-angular2-firebase package,
33 error not with npm itself.
33 error Tell the author that this fails on your system:
33 error     ./bin/postbuild.copy-assets.sh
33 error You can get information on how to open an issue for this project with:
33 error     npm bugs todo-angular2-firebase
33 error Or if that isn't available, you can get their info via:
33 error     npm owner ls todo-angular2-firebase
33 error There is likely additional logging output above.
34 verbose exit [ 1, true ]

**Comment by foxjazz** [comment]
it looked like failed on the post build script, but ran it manually.  this was failed on powershell and gitbash
